default_language_version:
    python: python3

repos:
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.28.0
      hooks:
          - id: gitleaks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
            exclude: ^assets/.*\.html$
          - id: check-yaml
            exclude: ^mkdocs.yml$
          - id: check-toml
          - id: check-merge-conflict
    - repo: https://github.com/pylint-dev/pylint
      rev: v4.0.2
      hooks:
          - id: pylint
            files: \.py$
            additional_dependencies:
                - bs4
                - DateTime
                - playwright
                - PyGithub
                - pytest
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.34.1
      hooks:
          - id: check-github-workflows
          - id: check-dependabot

ci:
    autofix_commit_msg: "chore(ci): [pre-commit.ci] autofix"
    autofix_prs: true
    autoupdate_branch: master
    autoupdate_commit_msg: "chore(ci): [pre-commit.ci] autoupdate"
    autoupdate_schedule: monthly
    autoupdate_timezone: Asia/Kolkata
    submodules: false
